name: "Inform Incompatible PRs"
on:
  pull_request:
    branches:
      - main

jobs:
  Check-Compatibility:
    runs-on: macos-latest
    steps:

      - name: Checkout-Main
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}

      - name: Checkout-HEAD
        uses: actions/checkout@v2 
        with: 
          path: ${{ github.head_ref }}
        
      - name: Setup Go Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install-Tools
        run: |
          cd ${{ github.base_ref }}
          make install-tools 
      
      # Generate apidiff states of Main
      - name: Generate-apidiff-States
        run: |
          cd ${{ github.base_ref }}
          make apidiff-build
      
      # Generate apidiff states of PR
      - name: Compare-apidiff-States
        run: |
          cd ${{ github.head_ref }}
          make apidiff-compare APICOMPARE_OPTS="../${{ github.base_ref }}/internal/data/apidiff"
      
      # Fail GitHub Action if there are incompatible changes
      - name: Check-apidiff-States
        run: |
          cd ${{ github.head_ref }}
          make apidiff-compare APICOMPARE_OPTS="../${{ github.base_ref }}/internal/data/apidiff"
