# This GitHub action will fail
#
#
name: "Inform Incompatible PRs"
on:
  pull_request:
    branches:
      - main

jobs:
  Check-Compatibility:
    runs-on: macos-latest
    steps:
      - name: Checkout-Main
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}

      - name: Checkout-HEAD
        uses: actions/checkout@v2 
        with: 
          path: ${{ github.head_ref }}
      
      - name: Setup Go Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH

      - name: Install-Tools
        run: |
          cd ${{ github.head_ref }}
          make install-tools 

      # Generate apidiff states of Main
      - name: Generate-apidiff-States
        run: |
          pwd
          cd ${{ github.head_ref }}
          pwd
          make apidiff-build-GA pkg_dir="../${{ github.base_ref }}"
        
      # Generate apidiff states of PR
      - name: Generate-apidiff-States
        run: |
          pwd
          cd ${{ github.head_ref }}
          pwd
          make apidiff-build-GA pkg_dir="../${{ github.head_ref }}"
 
      # Compare apidiff states of PR to Main
      - name: Compare-apidiff-States
        run: |
          pwd
          cd ${{ github.head_ref }}
          pwd
          make apidiff-compare-GA pkg_dir="../${{ github.base_ref }}"
      
      # Fail GitHub Action if there are incompatible changes
      - name: Check-apidiff-States
        run: |
          pwd
          cd ${{ github.head_ref }}
          pwd
          make apidiff-check pkg_dir="../${{ github.base_ref }}"
