# This GitHub action will fail
#
#
name: "Inform Incompatible PRs"
on:
  pull_request:
    branches:
      - main

jobs:
  Check-Compatibility:
    runs-on: macos-latest
    steps:
      - name: Checkout-Main
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}

      - name: Checkout-HEAD
        uses: actions/checkout@v2 
        with: 
          path: ${{ github.head_ref }}

      - name: Install-Tools
        run: |
          cd ${{ github.head_ref }}
          make install-tools 
        
      - name: Generate-apidiff-States
        run: |
          cd ${{ github.head_ref }}
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          make apidiff-build
      
      - name: Compare-apidiff-States
        run: |
          cd ${{ github.head_ref }}
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          make apidiff-compare-GA pkg_dir="../${{ github.base_ref }}/" input_dir="./internal/data/apidiff"
      
      # Fail GitHub Action if there are incompatible changes
      - name: Check-apidiff-States
        run: |
          cd ${{ github.head_ref }}
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          make apidiff-check pkg_dir="../${{ github.base_ref }}/" input_dir="./internal/data/apidiff"
