#
#
#
name: "Inform Incompatible PRs"
on:
  pull_request:
    branches:
      - main

jobs:
  Check-Compatibility:
    runs-on: macos-latest
    steps:
      - name: Checkout-Main
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}

      - name: Checkout-HEAD
        uses: actions/checkout@v2 
        with: 
          path: ${{ github.head_ref }}

      - name: Install-Tools
        run: |
          cd ${{ github.base_ref }}
          make install-tools 
        
      - name: Generate-Compare-Check-apidiff
        run: |

          # Set environment
          cd ${{ github.head_ref }}
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH

          # Generate apidiff states of PR
          echo ::group::Generating apidiff states
          make apidiff-build
          echo ::endgroup::
          
          # Compare apidiff states of PR to main
          echo ::group::Comparing apidiff states
          make apidiff-compare-GA pkg_dir="../${{ github.base_ref }}" input_dir="./internal/data/apidiff"
          echo ::endgroup::

          # Fail Github Action if there are incompatible changes
          echo ::group::Checking incompatible apis
          make apidiff-check pkg_dir="../${{ github.base_ref }}" input_dir="./internal/data/apidiff"
          echo ::endgroup::
